name: Javadoc CI

on:
  workflow_run:
    workflows: ["Release Version"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  javadoc:
    if: ${{ github.repository_owner == 'yL3oft' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build & generate Javadoc
        run: mvn clean javadoc:javadoc

      - name: Get project version
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload target artifact
        uses: actions/upload-artifact@v4
        with:
          name: zAPI ${{ steps.get_version.outputs.version }} Javadocs
          path: target/