name: Javadoc CI

on:
  workflow_run:
    workflows: ["Release Version"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  javadoc:
    if: ${{ github.repository_owner == 'yL3oft' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build & generate Javadoc
        run: |
          mkdir -p target/reports/apidocs
          cp sources/logo.png target/reports/apidocs/logo.png

          mvn clean javadoc:javadoc \
            -Djavadoc.additionalOptions="\
              -header '<a href=\"../index.html\" style=\"font-size:14px;padding:6px 10px;background:#0077cc;color:white;border-radius:6px;text-decoration:none;\">⬅ Back to Home</a>\
              <link rel=\"icon\" type=\"image/png\" href=\"logo.png\">' \
              -bottom '<link rel=\"icon\" type=\"image/png\" href=\"logo.png\">'"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
          external_repository: yL3oft/zPlugins
          publish_branch: gh-pages
          publish_dir: target/reports/apidocs
          destination_dir: zAPI